# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Fernando Bellido Pazos
title: Mathematician and Computer Scientist
email: fbellidopazos@gmail.com
website: https://fbpazos.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  fbpazos
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: fbellidopazos
tiktok_username: fbpazos
# instagram_username: fbpazos
# youtube_username: "@fbell"
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: tiktok
#  icon: fas fa-globe
#  url: https://www.tiktok.com/@fbpazos
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-M63WSJK6VF"
#google_analytics: "G-M63WSJK6VF"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Fernando Bellido and I'm a driven and dedicated professional with a strong work ethic and excellent interpersonal skills. I am a confident communicator who excels at collaborating with multidisciplinary teams, and I am always seeking to improve my abilities and grow as a professional. My natural enthusiasm and self-motivation make me a responsible and reliable team player who is able to effectively handle criticism to achieve success.
  
  I am most skilled in: <mark>Python</mark> and <mark>Mathematics</mark>

  Download my CV:
    - [English](files/CV - FernandoBP - ENG.pdf)
    - [Spanish](files/CV - FernandoBP - ESP.pdf)

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Data Analyst and Developer
        link: https://oeg.fi.upm.es/
        link_text: oeg.fi.upm.es
        sub_title: Madrid, Spain
        caption: September 2021 - January 2022
        description: | # this will include new lines to allow paragraphs
            ## Ontology Engineering Group
            ---
            Responsible for analysing academic papers stored in institutional repositories and implementing a system to create knowledge graphs and perform queries to address questions regarding Open Science principles.        

            Technologies used: Python, Pandas, SPARQL, RDF, MorphKGC
      - layout: left
        title: Developer
        link: https://savestarsconsulting.com/
        link_text: savestarsconsulting.com
        sub_title: Madrid, Spain
        caption: Summer 2021
        description: | # this will include new lines to allow paragraphs
            ## SaveStars Consulting
            ---
            Constructed a python-based system to retrieve images from NASA's VNP46A2 satellite, process the images, and apply a mask for a specified area of the peninsula to determine the level of light pollution in that specific region.

            Technologies used: Python, GDAL, Matplotlib, Numpy

      - layout: left
        title: Developer
        link: https://osoc.be/
        link_text: osoc.be
        sub_title: Madrid, Spain
        caption: Summer 2021
        description: | # this will include new lines to allow paragraphs
            ## Open Summer of Code
            ---
            Collaborating with a diverse team with the goal of supporting the 2030 Agenda to achieve a better future. Designed a Web-App that objectively assesses and evaluates tabular data from a user-specified data source obtained from open data portals (e.g. datos.gob.es).

            Technologies used: Python, SPARQL, FastAPI, NoSQL
      
      - layout: left
        title: Developer
        link: https://osoc.be/
        link_text: osoc.be
        sub_title: Madrid, Spain
        caption: Summer 2020
        description: | # this will include new lines to allow paragraphs
            ## Open Summer of Code
            ---
            Collaborating with a cross-functional team to contribute to a brighter future for the 2030 agenda. 
            Designing a WebApp that provides personalized recommendations for good habits based on data related to the global pandemic, which has been gathered, analyzed and presented through visually appealing graphs.

            Technologies used: Python, Grafana, Numpy, SQL

      - layout: left
        title: Web Developer and Technical Support 
        link: https://www.bblur.com/
        link_text: bblur.com
        sub_title: London, United Kingdom
        caption: July 2019 - August 2019
        description: | # this will include new lines to allow paragraphs
            ## BBLUR Architecture 
            ---
            Involved in the revamp of the company's website utilizing WIX (enterprise-level solution) and providing technical assistance to the company, focusing mainly on hardware support.

      - layout: left
        title: Web Developer and Technical Support
        link: https://trilogygroup.com/
        link_text: trilogygroup.com
        sub_title: Cheltenham, United Kingdom
        caption:  July 2018 - August 2018
        description: | # this will include new lines to allow paragraphs
            ## Trilogy Group Limited 
            ---
            Participating in the redevelopment of the company's website utilizing WordPress (enterprise-level platform) and offering technical support to the company.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad Carlos III de Madrid
        link: https://www.uc3m.es/master/applied-mathematics
        link_text: uc3m.es/master/applied-mathematics
        caption: 2022 - 2023
        sub_title: English
        description: | # this will include new lines to allow paragraphs
          ## MSc in Applied & Computational Mathematics 
          ---
          * Average grade: 8/10 with 1 Honorable Mention on Advanced Methods in Analysis.

          * Courses: Biological Inspired Artificial Intelligence, Perspectives on Applied & Computational Mathematics, Computational Algebra, Computational techniques for differential equations, Special functions & Orthogonal Polynomials, Advanced Methods for non-linear differential equations and Biological & Socioeconomic Systems, Stochastic Equations for Finance and Biology.

          * Master's Description: The Master’s Degree in Computational and Applied Mathematics offered by Universidad Carlos III de Madrid responds to such a demand, by emphasizing a double, computational and mathematical, approach to solving realistic problems, offering multidisciplinar education to holders of STEM Bachelor degrees which, from a solid basic training, is oriented towards the development of quantitative and computational methods which can be applied to a wide spectrum of disciplines.


      - layout: left
        title: Universidad Politécnica de Madrid
        link: http://www.fi.upm.es/?id=gradomatematicasinformatica&idioma=english
        link_text: fi.upm.es/?id=gradomatematicasinformatica
        caption: 2018 - 2022
        sub_title: Spanish
        description: | # this will include new lines to allow paragraphs
          ## BSc in Mathematics and Computer Science
          ---
          * Average grade: 9.4/10 with 14 Honorable Mentions.

          * Courses: Databases, Operative Systems, Data Structures, Data Analytics, Artificial Intelligence, Programming (Object Oriented, imperative, functional and logic), Functional Analysis, Applied \& Computational Topology and Pure Mathematics.

          * Degree Description: The ultimate purpose of the degree is to know the nature, methods, and most relevant purposes of Mathematics, and to have general knowledge of Computer Science and the interrelation between both disciplines. 
                                Companies in the I.T. sector, such as IBM, have noted the growing demand for professionals with good knowledge of computing and mathematics, who can also serve as a link between experts in the two disciplines.
      
      - layout: left
        title: Trinity College San Sebastían de los Reyes
        link: https://trinitycollegessreyes.es/
        link_text: trinitycollegessreyes.es
        caption: 2018 - 2022
        sub_title: Spanish
        description: | # this will include new lines to allow paragraphs
          ## Baccalaureate in Technological Sciences
          ---
          * Average grade: 13.46/14 with 5 Honorable Mentions.

          * Courses: Mathematics, Physics, Technical Drawing, Information Technology, Industrial Engineering and Psychology.



  - title: Projects # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      ## Basic Numerical Methods in Python - Student Oriented (2023)
      ---
      The focus of my Master's thesis is to create an open-source PyPi project that features fundamental numerical methods commonly taught in universities, but simplified for easy student comprehension without unnecessary code for improved algorithm efficiency.

      This project not only includes a script version of the methods, but also features a Jupyter-based graphical user interface, allowing students to observe the algorithm in real-time based on their input.

      The objective of this project is to provide students with a basic understanding of the implemented numerical methods and to introduce them to Python, as opposed to MATLAB which requires a fee and is not as widely used in the programming job market as Python is.

      * Tech: Python, Jupyter, Numpy, BQPlot, iPyWidgets
      * Link: [github.com/fbpazos/Trabajo-Fin-Master](https://github.com/fbpazos/Trabajo-Fin-Master)

      ## The Sturm-Liouville problem and models based on differential equations in the field of acoustics (2022)
      ---
      Pursued a comprehensive study of the Sturm-Liouville theory and modeled stringed musical instruments to explore the relationship between mathematics and music. The aim of the research was to answer questions such as: what factors contribute to the distinct sound of instruments like a violin and a piano, and how does mathematics play a role in the creation of music.
      
      * Tech: Python, Latex, Matplotlib, Plotly, Sympy, NumPy,Jupyter, Differential Equations, Functional Analysis.
      * Link: [oa.upm.es/70879](https://oa.upm.es/70879/)

    
      ## S.I.R. Modelling in Python (2021)
      ---
      Involved in research-focused, open-source analysis of Covid-19 to gain insight into the mathematical models of the S.I.R. (Susceptible, Infected, Recovered) dynamics during the pandemic.

      The objective of this analysis was to gain a deeper understanding of the spread of the virus and its impact on populations, using mathematical models to inform the findings.

      * Tech: Python, Jupyter
      * Link: [github.com/fbellidopazos/covidSIRAnalysis](https://github.com/fbellidopazos/covidSIRAnalysis)

  - title: Honors and Awards # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        ## • Cambridge English Advanced Certificate
        ## • Academic Excellence Grant 2021 & 2022
        ## • Academic Excellence Award for Representative Agents of Banco Mediolanum 2022
  

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in mathematics and computer science some of my other interests and hobbies are:
      ## Violin
      ---
      With 2.5 years of experience playing the violin and daily practice of 2 hours per day, I have honed my skills in instrument playing, musical notation reading, and completed additional coursework in music theory.

      As a member of an orchestra, I participated in the European Youth Music Week 2022 in Oakham, United Kingdom. I am also a member of a musical group at Escuela de Sol Menor.

      **Concerts**
      * Salut d'Amour (to Carice) - Edward Elgar (December 2022): [youtube.com/watch?v=Bhm1K_2bTYQ](https://www.youtube.com/watch?v=Bhm1K_2bTYQ)
      * Double Violin Concerto (BWV 1043) - J.S. Bach (June 2022): [youtube.com/watch?v=j81yxB_dy_E](https://www.youtube.com/watch?v=j81yxB_dy_E)
      * Opus 34, First Movement - Oskar Rieding (December 2021): [youtube.com/watch?v=35g-lyy-INw](https://www.youtube.com/watch?v=35g-lyy-INw)

      ## Swimming
      ---
      I have a commitment to maintaining a healthy and active lifestyle and prioritize regular physical activity, including swimming at least once a week. With 5 years of experience in the sport, I have developed strong swimming skills and the ability to swim for longer periods of time with endurance.
       
      
      



# Footer 
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
